### ISSUE TITLE
Tests aren't running in GitHub for the project

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_project#105]

**Comment by stephen-cox** [comment]
![image](https://user-images.githubusercontent.com/7189914/215504958-8b605b7c-8944-4e81-8435-5a038791e809.png)

**Comment by stephen-cox** [comment]
I have re-enabled them - should run overnight tonight

**Comment by finnlewis** [comment]
They are indeed now running, thanks @stephen-cox !

(Now we just need to fix the latest test failures https://github.com/localgovdrupal/localgov_project/actions/runs/4051610712/jobs/6970125946#step:5:14 )
