### ISSUE TITLE
Should we add patchlevel directive in this project composer.json?

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_project#150]
See https://github.com/cweagans/composer-patches/issues/423#issuecomment-1298697563
```json
  "extra": {
    "patchLevel": {
      "drupal/core": "-p2"
    }
  }
```

I'm running into issues applying some patches after upgrading to macOS 14.
Some repos include this already, but maybe it should be at the project level?

**Comment by millnut** [comment]
I agree with @andybroomfield that this should be included by default, it also fixes the issue I'm experiencing here https://github.com/localgovdrupal/localgov_services/pull/238#issuecomment-1915225964 with patches that create new files causing nesting.

**Comment by stephen-cox** [comment]
Tested this on Linux and the suggested change still works, so if this fixes things for Mac users looks fine to be made into a PR.

**Comment by cweagans** [comment]
FYI, this won't be necessary for composer-patches v2. `drupal/core` defaults to this value.

**Comment by cweagans** [comment]
(Testing with v2 is appreciated, btw! `composer require cweagans/composer-patches:"2.0.0-beta2 as 1.7"` is more or less all you'd need)
