### ISSUE TITLE
Request to add Localgov_alert_banner to distribution

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_project#16]
Initial port of alert banner is now ready.

I need authorisation to add to packagist

**Comment by ekes** [comment]
https://packagist.org/packages/localgovdrupal/localgov_alert_banner

I can add you as well if you have a packagist user name. 
Not sure why it's not picking up the license.

**Comment by andybroomfield** [comment]
Thanks @ekes

**Comment by finnlewis** [comment]
Is this resolved @andybroomfield ?

**Comment by andybroomfield** [comment]
@finnlewis Have to set up the pull request on localgov.
