### ISSUE TITLE
You have requested a non-existent service "cache.backend.null".

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_project#19]
On a fresh install, I am getting the following error:
```

$ lando drush si localgov -y;

 // You are about to DROP all tables in your 'database' database. Do you want to continue?: yes.                        

 [notice] Starting Drupal installation. This takes a while.

In ContainerBuilder.php line 1060:
                                                                   
  You have requested a non-existent service "cache.backend.null".  
```
To suppress the error and install the site I need to comment out 

https://github.com/localgovdrupal/localgov_project/blob/master/assets/composer/settings.lando.php#L69
https://github.com/localgovdrupal/localgov_project/blob/master/assets/composer/settings.lando.php#L91
https://github.com/localgovdrupal/localgov_project/blob/master/assets/composer/settings.lando.php#L100

**Comment by ekes** [comment]
$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/development.services.yml';

Should have included 
https://git.drupalcode.org/project/drupal/-/blob/8.9.x/sites/development.services.yml#L8

Assume these are all there on your local checkout?

**Comment by finnlewis** [comment]
Not had this issue since... can't recall what happened to be honest!
