### ISSUE TITLE
.lando.dist.yml

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_project#22]
Lando supports [distribution specific config files](https://docs.lando.dev/config/lando.html#base-file).  Perhaps we can consider this approach given that LocalGov Drupal is a distribution.  Implementation would involve:
- Rename current .lando.yml to .lando.dist.yml (or .lando.base.yml or .lando.upstream.yml)
- Provide an empty .lando.yml.  I am not entirely sure if we must have a .lando.yml file for Lando to function.  If not, we don't even need to provide any .lando.yml file.

If we take this approach, it would be easier for individual sites to override the distribution specific Lando config.  For example, we at Croydon use a custom Docker image as the "appserver" instead of LocalGov's default "appserver" image.  I am currently doing so from .lando.local.yml.  But the Lando [documentation says](https://docs.lando.dev/config/lando.html#override-file) this file should be used for personal tweaks rather than project specific ones.  Having a distribution specific Lando file should help resolve this.

FAO @stephen-cox @finnlewis

**Comment by stephen-cox** [comment]
Renaming `.lando.yml` to `.lando.dist.yml` is enough to deal with this use case and seems like a good idea to me. I've just checked on my local machine and renaming the file is enough.

**Comment by Adnan-cds** [comment]
> I've just checked on my local machine and renaming the file is enough.

Thanks for trying Steve.  I will try to raise a pull request by this Friday :)

**Comment by finnlewis** [comment]
Nice idea @Adnan-cds !

I've tested locally too and created the pull request for review.
