### ISSUE TITLE
CodeSniffer is suffering PHP Fatal errors

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_project#23]
Test runs are [failing](https://github.com/localgovdrupal/localgov_theme/pull/117/checks?check_run_id=1298419775#step:9:15) due to issues with [PHP Code sniffer](https://github.com/squizlabs/PHP_CodeSniffer/).  It had [two releases](https://github.com/squizlabs/PHP_CodeSniffer/tags) in the last 4 days and these releases (3.5.7, 3.5.8) are leading to this fatal error.  Version 3.5.6 works okay.  I am wondering if we need to pin squizlabs/php_codesniffer to 3.5.6.

### How to reproduce
```
$ composer create-project --stability dev localgovdrupal/localgov-project
$ pushd localgov-project
$ ./bin/phpcs # this leads to the PHP fatal error
$ composer require --dev squizlabs/php_codesniffer:3.5.6
$ ./bin/phpcs # This one should be alright
$ echo $?
```

FAO @stephen-cox @finnlewis

**Comment by finnlewis** [comment]
I've got no objections to pinning squizlabs/php_codesniffer to 3.5.6. for now if that's the quicker way to prevent eroneously failing tests.

**Comment by stephen-cox** [comment]
We've already has to pin PHP Stan for a similar reason (https://github.com/localgovdrupal/localgov_project/blob/350857e8f71e54f43363db8abc1a67f3d5887ceb/composer.json#L26) so no objections to pinning Code Sniffer

**Comment by Adnan-cds** [comment]
Thanks, I will try to raise a pull request today given the urgency of the matter.
