### ISSUE TITLE
PHP 7.2 is no longer supported

### ISSUE THREAD

**Issue by tanc** [localgovdrupal/localgov_project#34]
PHP `7.2` is longer a supported version: https://www.php.net/supported-versions.php

We should update to `7.4` as even `7.3` will be only security updates from tomorrow, for one year.

**Comment by andybroomfield** [comment]
Agreed, best to move and develop agaisnt php 7.4 as we will also need to plan for php 8 at some point.

**Comment by finnlewis** [comment]
Agreed!

**Comment by ekes** [comment]
Lando now running 7.4
CI Tests now running 7.4

I guess this can be closed?
