### ISSUE TITLE
Adminer not working in Lando

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_project#44]
Getting connection refused? anyone else?

On http://adminer.localgov.lndo.site:8000/

**Comment by danchamp** [comment]
It only works for me without specifying the port.

**Comment by andybroomfield** [comment]
I just get:
It Works!
From Webserver

**Comment by stephen-cox** [comment]
When you start Lando it should display a list of URLs and Adminer should be listed there with: http://adminer.localgov.lndo.site/

At least that's what I'm seeing

**Comment by andybroomfield** [comment]
I get the port number version. But it always refuses to connect (and the one without the port number just displays the It works message).

**Comment by stephen-cox** [comment]
I suspect Lando is conflicting with something on port 80 (so using 8000) and the Adminer config is not setup to handle connections coming from something other than port 80. Will need a little investigation to see whether it's possible to fix

**Comment by andybroomfield** [comment]
I just tried shutting down local apache, and restart lando.
Whilst it now says port 80, I'm getting the same connection refused error.

**Comment by stephen-cox** [comment]
Does a `lando rebuild` help? This can fix things if they get out of sync

**Comment by andybroomfield** [comment]
I tried that, still no joy. I'm convinced it's because I have a setup of using regular Apache for main development and Lando for localgov drupal only

**Comment by finnlewis** [comment]
Hey @andybroomfield 

Is this still an issue for you?

**Comment by andybroomfield** [comment]
@finnlewis Yeah I'm still having trouble accessing, was checking if anyone else did.

**Comment by finnlewis** [comment]
Adminer works for me every time. Is this still bugging you @andybroomfield ?

**Comment by andybroomfield** [comment]
@finnlewis TBH I gave up on Lando and just devlop nativley now.

**Comment by finnlewis** [comment]
Fair play - let's close this off then!
