### ISSUE TITLE
Add the patch to support referencing unpublishing entities

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_project#58]
See core patch
https://www.drupal.org/project/drupal/issues/2845144

See 
https://github.com/localgovdrupal/localgov/issues/334

Apply this patch, but it should be on the project / profile?
https://github.com/localgovdrupal/localgov_guides/pull/71

**Comment by finnlewis** [comment]
Hey @andybroomfield 

is this covered by https://github.com/localgovdrupal/localgov/pull/336 ? 

Cheers,

Finn

**Comment by andybroomfield** [comment]
I believe so, just check to see if there are related issues.
