### ISSUE TITLE
node version 10 is a legacy version! We recommend upgrading.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_project#63]
When installing Lando, I'm seeing 

`node version 10 is a legacy version! We recommend upgrading.`

We should update it. 

I'm not sure if we actually need node, these days, it was used before to compile scss into css and other front-end build processes.

**Comment by andybroomfield** [comment]
Still required by localgov_theme so it depends on when that is going to be removed.

**Comment by finnlewis** [comment]
Good point @andybroomfield :)
