### ISSUE TITLE
Run tests every night

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_project#79]
Now we're only running the tests included in a specific module / profile / theme, we're not longer running all tests apart from when there are changes to the project. We should run the tests here nightly so we get alerted when things fail.

Question: What sort of notifications do we want? We could send a bunch of emails. More useful (less spammy) might be to have a Slack channel for these alerts.

**Comment by finnlewis** [comment]
I'm happy to get updates by email every day!

**Comment by stephen-cox** [comment]
Turns out sending emails is not straightforward. Slack notifications are likely easier.

I have created a PR to add a run at 7am #85. No notifications yet

**Comment by finnlewis** [comment]
Hey @stephen-cox  - are we now running tests every night? If so could I get notifications. @ekes and I were interested that the first we heard of the failing tests on https://github.com/localgovdrupal/localgov_project/runs/7320775021?check_suite_focus=true was on that PR. I will track those issues up separately either way

**Comment by stephen-cox** [comment]
@finnlewis There's a PR to run tests night #85

Tests have been failing for a while and have told people about them. Remaining issues are https://github.com/localgovdrupal/localgov_services/issues/170 and https://github.com/localgovdrupal/localgov/issues/451

I've looked at notifications and there's not a simple solution. It's actually looks easier to post stuff to a Slack channel than send email. Need to find the time to look at implementing something

**Comment by finnlewis** [comment]
Tests are running nightly, so closing this. Thanks @stephen-cox !
