### ISSUE TITLE
Ignore composer.lock in .gitignore

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_project#8]
Should we ignore composer.lock?
As this is the basis for building new sites rather than a fixed project, it makes sense to have the lock file ignored?

**Comment by stephen-cox** [comment]
Agreed - have been wondering what to do about it.

**Comment by finnlewis** [comment]
@Adnan-cds mentioned today that committing the composer.lock file potentially made it easier for developers to get set up on the project as it reduces the composer overhead making the first composer install quicker. 

I've been reading a little on this.
Geerling suggests it is good: 
https://www.jeffgeerling.com/blog/2017/tips-managing-drupal-8-projects-composer

Composer docks suggest it is good: 
https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file

Just flagging this as it might want to be reviewed. 

What do other distributions do?

**Comment by finnlewis** [comment]
@ekes pointed us to https://github.com/acquia/lightning-project#source-control 

> When you set up the project, Composer will create a file called composer.lock, which is a list of which dependencies were installed, and in which versions. Commit composer.lock to source control! Then, when your colleagues want to spin up their own copies of the project, all they'll have to do is run composer install, which will install the correct versions of everything in composer.lock.

Suggesting that it is left to the team who install the distribution to manage their lock file, rather than ship the distribution with a lock file.

**Comment by andybroomfield** [comment]
Just a quick check, is this the project composer.lock (from composer create-project localgovdrupal/localgov) or the composer.lock inside the localgov distribution?

It would make sense to have a .lock with the distribution as typically they do tend to lock versions of modules to guarantee compatibility. However I would be cautious of doing that with the project as typically someone would want to make it their own thing by adding their own modules, unless I've misunderstood the issue.

**Comment by stephen-cox** [comment]
We don't want a committed composer.lock file in the project. Once creating a site using this distribution you will want to commit the composer.lock file.

Closing this, but we can re-open if there's a further discussion here.
