### ISSUE TITLE
Remove node container service from default Lando file

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_project#96]
I'm pretty sure we don't need the node container.

https://github.com/localgovdrupal/localgov_project/blob/2.x/.lando.dist.yml#L42-L48

Any reason to keep it @ekes @stephen-cox ?

**Comment by ekes** [comment]
Pretty sure we already agreed to remove it. Is this what happens when you forget to make a ticket after agreeing a thing?
