### ISSUE TITLE
Use mariadb in Lando - for all the reasons

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_project#99]
At the moment just

```
config:
  xdebug: true
  database: mariadb
```

_Originally posted by @ekes in https://github.com/localgovdrupal/localgov_project/issues/97#issuecomment-1387352302_

**Comment by finnlewis** [comment]
@ekes any reason we shouldn't move to mariadb as default in lando?

**Comment by ekes** [comment]
The only thing I can think of is swapping it might be disruptive for someone? Like you'll loose you db when you rebuild.

As I'm already using it it won't be disruptive to me :)

**Comment by millnut** [comment]
Correct @ekes it would destroy the database locally and you'll loose the data on a rebuild. However I think we should ensure that we are consistent as [ddev](https://github.com/localgovdrupal/localgov_project/blob/3.x/.ddev/config.yaml#L12) uses mariadb so it makes sense for lando to use the same.

@finnlewis maybe we can flag on Slack or the next technical meeting that we are planning to switch to mariadb for lando to ensure consistency with local development tools?
